### ISSUE TITLE
The generator imposter data's code

### ISSUE THREAD

**Issue by pribadihcr** [huangshiyu13/RPNplus#1]
Hi @huangshiyu13,

When the generator data is available ?

Thanks

**Comment by huangshiyu13** [comment]
If you mean the synthetic dataset, I have already put it here: https://drive.google.com/open?id=0BzU4ETbYHM6feVM2ZE9qNzVxeHM

**Comment by pribadihcr** [comment]
I mean the tool to generate a massive amount of synthetic data and thw code for training a discriminative classifier to select a realistic subset (that fools the classifier).

**Comment by huangshiyu13** [comment]
We are not going to release the Unity3D code and 3D models, because of the copyright issues. As for the discriminator, we said in the paper that we use the vgg16 network, which is not our contribution, so we will not provide the code here.  If you want to use the vgg16 network, we recommend this repository : https://github.com/machrisaa/tensorflow-vgg
